AllCops:
  Exclude:
    - 'vendor/**/*' # need for travis-ci
    # http://caseywest.com/faster-ci-on-travis-and-docker-for-ruby-and-rails-and-rubocop/

AllCops:
  TargetRubyVersion: 2.2

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 17
